# Me
firstName: Branden
lastName: Higby

email: contact@brandenhigby.com

twitter_username: higby_
github_username:  higby
instagram_username: higby_

# Site
description: A collection of Branden Higby's ramblings.

collections:
  internal:
    output: true
    permalink: /:path.html
  external:
    output: false

collections_dir: pages

defaults:
  - scope:
      path: ""
    values:
      layout: "post" #Asssume post layout if not specififed

  - scope:
      path: "_internal/hidden/"
    values:
      hidden: "true"
      permalink: "/:title.html"

  - scope:
      path: "_internal/root/"
    values:
      hidden: "true"
      permalink: "/:title.html"

plugins:
  - jekyll-redirect-from
