# Personal
title: Branden Higby
email: contact@brandenhigby.com
twitter_username: higby_
github_username:  higby
instagram_username: higby_

# Site
source: src
description: >-
  A collection of Branden Higby's ramblings.
url: "https://higby.io"

defaults:
  - scope:
      path: ""
    values:
      layout: "page" # All pages use page layout unless otherwise told

collections:
  pages:
    output: true
    permalink: /:title.html

plugins:
  - jekyll-tidy
  - jekyll-tagories
  - jekyll-sitemap
  - jekyll-target-blank

sass:
    style: expanded
    sourcemap: never
    sass_dir: assets/css/_sass

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
