firstName: Branden
lastName: Higby
email: contact@brandenhigby.com
twitter_username: higby_
github_username:  higby
instagram_username: higby_

description: A collection of Branden Higby's ramblings.

collections:
  writing:
    output: true
    permalink: /:path.html
  root:
    output: true
    permalink: /:path.html
  external:
    output: false
collections_dir: site
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_writing/hidden/"
    values:
      hidden: true

plugins:
  - jekyll-redirect-from
  - jekyll-tidy
