title: Branden Higby
email: contact@brandenhigby.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of Branden Higby's ramblings.
baseurl: ""
url: "https://higby.io"
twitter_username: higby_
github_username:  higby
instagram_username: higby_

plugins:
  - jekyll-redirect-from
  - jekyll-tidy
  - jekyll-tagories
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-loading-lazy

collections:
  work:
    output: true
    permalink: /:title.html

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - README.md
  - CNAME
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
