[build]
  command = 'npm run build'
  publish = 'build'
  functions = 'src/functions'

[dev]
  command = 'npm run start'

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200