[build]
  command = 'npm run build'
  publish = 'build'
  functions = 'src/functions'

[dev]
  command = 'npm run start'

[[redirects]]
  from = 'functions/cache/garden/*'
  to = '/garden/:splat'
  status = 301
  force = true

[[redirects]]
  from = '/garden/*'
  to = '/.netlify/functions/garden'
  status = 200

[functions]
  included_files = ["build/functions/cache/**"]