# Personal
title: Branden Higby
email: branden@higby.io
github_username:  higby
instagram_username: higby_

# Site
source: site
destination: _build
description: >-
  A collection of Branden Higby's ramblings.
url: "https://higby.io"
timezone: America/Los_Angeles

defaults:
  - scope:
      path: ""
    values:
      layout: "page" # All pages use page layout unless otherwise told

collections_dir: garden
collections:
  petals:
    output: true
    permalink: /:path.html
  years:
    output: false

kramdown:
  footnote_backlink: "^"

plugins:
  - jekyll-liquify
  - jekyll-tagories
  - jekyll-target-blank
  - jekyll-tidy

jekyll_tidy:
  exclude:
    - robots.txt
    - _redirects

sass:
    style: compact
    sourcemap: never
    sass_dir: assets/css/_sass

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _redirects
