name: Build and deploy jekyll site

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - name: setup
        uses: actions/checkout@v2

      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # can change this to 2.7 or whatever version you prefer

      - name: install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ETHERIA }}
          publish_dir: ./_site
